mysql:

  # DATABASE CONNECTION

  direction: "localhost"
  port: "3306"
  database: "game"
  SSL: false

  # DATABASE CREDENTIALS

  username: "server"
  password: "Wow, Amazing Password"

general:
  debug: false

server_stats:
  enable: true
  delay: 120 # update every 2 mins (120 seconds)
  server_name: general # server push id (don't change if you're not using bungee)
